name: CompassTracker
version: 2.0
main: me.subhanafz.compasstrack.compasstracker.CompassTracker
api-version: 1.13
description: CompassTracker
commands:
  giveCompass:
    description: Gives you a compass
    usage: /<command>
  addSpeedrunners:
    description: Adds a speedrunner to the Speedrunner arraylist
    usage: /<command> [Player]
  getSpeedrunners:
    description: Prints out all of the speedrunners in the arraylist
    usage: /<command>
  removeSpeedrunners:
    description: Removes a speedrunner from the Speedrunner arraylist
    usage: /<command> [Player]
  startTracking:
    description: Toggle tracking of speedrunners
    usage: /<command>

