name: CompassTracker
version: 1.1
main: me.subhanafz.compasstrack.compasstracker.CompassTracker
api-version: 1.13
description: CompassTracker
commands:
  giveCompass:
    description: Gives you a compass
    usage: /<command>
  track:
    description: Makes compass Track a player
    usage: /<command> [PlayerName]
